# Generated by Django 4.1.7 on 2023-05-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.CharField(blank=True, max_length=30, verbose_name='provider'),
        ),
    ]
