"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# from django.contrib.staticfiles.storage import ManifestStaticFilesStorage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv(os.path.join(BASE_DIR, '.environ'))
SECRET_KEY = os.getenv('SECRET_KEY')




# Application definition

INSTALLED_APPS = [
    'compressor',
    'django_extensions',
    'htmlmin',
    'account',
    'tool_mail',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    # 'oauth_app',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'base.backends.EmailBackend',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '<your_google_client_id>'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '<your_google_client_secret>'

SOCIAL_AUTH_MICROSOFT_OAUTH2_KEY = '<your_office365_client_id>'
SOCIAL_AUTH_MICROSOFT_OAUTH2_SECRET = '<your_office365_client_secret>'

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
# STATICFILES_DIRS = [ os.path.join(BASE_DIR,'static') ]

# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#     'compressor.finders.CompressorFinder', # Add this line
# ]
# STATICFILES_CACHE_CONTROL = 'max-age=31536000'

# STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# """
# EMAIL SERVICES
# """
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@example.com'  # Replace with your Gmail email address
# EMAIL_HOST_PASSWORD = 'your_email_password'  # Replace with your Gmail email password
# """"""

# EXPIRES_DEFAULT = 'access plus 1 month'
# EXPIRES_IMAGES = 'access plus 1 year'
# EXPIRES_CSS = 'access plus 1 year'
# EXPIRES_JS = 'access plus 1 year'
# EXPIRES_FONTS = 'access plus 1 year'

# GZIP_COMPRESS_MIN_SIZE = 1024

# COMPRESS_ENABLED = False
# COMPRESS_OFFLINE = False
# COMPRESS_OUTPUT_DIR = 'compressed'
# COMPRESS_CSS_FILTERS = [
#     'compressor.filters.cssmin.CSSMinFilter',
# ]
# COMPRESS_JS_FILTERS = [
#     'compressor.filters.jsmin.JSMinFilter',
# ]
# COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'


